= JDG on Openshift with Hotrod and Security Enabled

=== Introduction

This demo aims to provide starting point/code-sample to configure and run Datagrid on Openshift with hotrod and authorization/authentication on

1. minishift v1.25.0+90fb23e
2. Openshift version v3.11.0
3. JBoss Datagrid Container Image 7.2
4. mvn 3.5.4

=== Run Demo
==== Step 1: Install minishift
Run following command to start minishift
----
$ minishift start --memory 8GB
----

==== Step 2: Download JBoss Datagrid Imagestream
----
$ oc login -u system:admin
$ oc project openshift
$ oc import-image registry.access.redhat.com/jboss-datagrid-7/datagrid72-openshift:1.3 --confirm
----

create 1.2 and latest tag
----
$ oc tag registry.access.redhat.com/jboss-datagrid-7/datagrid72-openshift:1.2 datagrid72-openshift:1.2
$ # tag latest to 1.3
$ oc tag registry.access.redhat.com/jboss-datagrid-7/datagrid72-openshift:1.3 datagrid72-openshift:latest
$
$ oc describe is/datagrid72-openshift
----
last command should show you three tags

==== Step 2: Create keystore

We need to create keystores holding self-sigend certificates. One for encrypting the client to datagrid communication and other for encrypting one jdg node to another jdg node communication.

Let's first create client to datagrid keystore named jdg-https.jks. There will be some questions asked, please enter the same ones as you see below

----
$ keytool -genkey -keyalg RSA -alias selfsigned -keystore jdg-https.jks -storepass changeit -validity 360 -keysize 2048

What is your first and last name?
  [Unknown]:  selfsigned
What is the name of your organizational unit?
  [Unknown]:  SG
What is the name of your organization?
  [Unknown]:  SG
What is the name of your City or Locality?
  [Unknown]:  SG
What is the name of your State or Province?
  [Unknown]:  SG
What is the two-letter country code for this unit?
  [Unknown]:  SG
Is CN=selfsigned, OU=SG, O=SG, L=SG, ST=SG, C=SG correct?
  [no]:  yes

Enter key password for <selfsigned>
  (RETURN if same as keystore password):  

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore jdg-https.jks -destkeystore jdg-https.jks -deststoretype pkcs12".
----

let's create jdg node to node keystore named jgroups.jceks

----
$ keytool -genseckey -alias selfsigned -keypass changeit -storepass changeit -keyalg Blowfish -keysize 56 -keystore jgroups.jceks -storetype JCEKS

Warning:
The JCEKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore jgroups.jceks -destkeystore jgroups.jceks -deststoretype pkcs12".
----

Create a secret now named datagrid-app-secret that would hold contents of both the keystores created above. The secret would be mounted to jdg deployment later on. 

----
$ oc create secret generic datagrid-app-secret --from-file=jdg-https.jks --from-file=jgroups.jceks
$ oc secrets link default datagrid-app-secret
----

==== Step 3: Deploy datagrid

First upload template that would deploy datagrid
----
$ oc project openshift
$ oc create -f templates/datagrid72-https.json
$ oc new-project jdg
$ oc create secret generic datagrid-app-secret --from-file=jdg-https.jks --from-file=jgroups.jceks
$ oc secrets link default datagrid-app-secret
$ oc new-app --template=datagrid72-https --name=rhdg  \
   -e CACHE_NAMES=mycache \
   -e MYCACHE_CACHE_START=EAGER \
   -e USERNAME=user1 \
   -e PASSWORD=welcome1 \
   -e ADMIN_GROUP=customrole \
   -e CONTAINER_SECURITY_ROLES="customrole=READ WRITE" \
   -e MYCACHE_CACHE_SECURITY_AUTHORIZATION_ENABLED="true" \
   -e MYCACHE_CACHE_SECURITY_AUTHORIZATION_ROLES="customrole" \
   -e REST_SECURITY_DOMAIN=jdg-openshift \
   -e HOTROD_AUTHENTICATION="true" \
   -e HOTROD_ENCRYPTION="true" \
   -e HOTROD_SERVICE_NAME=datagrid-app-hotrod \
   -e HTTPS_NAME=selfsigned \
   -e HTTPS_SECRET=datagrid-app-secret \
   -e HTTPS_KEYSTORE=jdg-https.jks \
   -e HTTPS_PASSWORD=changeit \
   -e JGROUPS_ENCRYPT_NAME=selfsigned \
   -e JGROUPS_ENCRYPT_SECRET=datagrid-app-secret \
   -e JGROUPS_ENCRYPT_KEYSTORE=jgroups.jceks \
   -e JGROUPS_ENCRYPT_PASSWORD=changeit

----

Following parameters are passed in the above command

*CACHE_NAMES* = This will create "mycache" in JDG

*USERNAME*/*PASSWORD* = To access JDG, username/password needs to be provided

*ADMIN_GROUP* = We create a new role, customrole, that we would assign privileges to

*CONTAINER_SECURITY_ROLES* = Here, we assign READ and WRITE privilege to customrole

*MYCACHE_CACHE_SECURITY_AUTHORIZATION_ENABLED* = This parameter (parameter starts with cache name, mycache, in CAPS) sets that authorization needs to be followed for mycache

*MYCACHE_CACHE_SECURITY_AUTHORIZATION_ROLES* = We assign customrole to MYCACHE cache

*HOTROD_AUTHENTICATION* = Sets to true

*HOTROD_ENCRYPTION* = Sets to true

*HOTROD_SERVICE_NAME* = This maps to the service name that Openshift assigns when we deploy the template

*HTTPS_NAME* = should match the "alias" we have set while creating keystore for client to server communication

*HTTPS_PASSWORD*/*JGROUPS_ENCRYPT_PASSWOR* = should match the storepass we have set while creating keystore for client to server communication

*HTTPS_SECRET*/*JGROUPS_ENCRYPT_SECRET* = should match the secret we have created in Step 2 above

*HTTPS_KEYSTORE*/*JGROUPS_ENCRYPT_KEYSTORE* = specifies which keystore should be refered to in the HTTPS_SECRET/JGROUPS_ENCRYPT_SECRET

*JGROUPS_ENCRYPT_NAME* = should match "alias" when we created the keystore for node to node communication

For more information on setting environment variables, refer to this link for 7.2 version

https://access.redhat.com/documentation/en-us/red_hat_data_grid/7.2/html/data_grid_for_openshift/os-env-vars#env-var-cache

Now, check that user1 has been assigned customrole.

----
$ oc get pods
NAME                   READY     STATUS      RESTARTS   AGE
datagrid-app-2-lkhjz   1/1       Running     0          16m

$ oc rsh datagrid-app-2-lkhjz

sh-4.2$ cd /opt/datagrid/standalone/configuration
sh-4.2$ ls
application-roles.properties  clustered-openshift.xml  mgmt-groups.properties  standalone.xml
application-users.properties  clustered.xml       mgmt-users.properties   standalone_xml_history
cloud.xml      logging.properties       services.xml

sh-4.2$ cat application-roles.properties
...
...
...
user1=customrole

## You will see that in this file user1 is assigned customrole.
----

==== Step 3: Deploy Hotrod Client

We will now deploy client application (SpringBoot) which will access JDG in secure mode. Have a look at following two files
1. HotrodController.java - This file exposes all urls

2. HotrodService.java - This file initialize cache. Have a look at this file to understand how we are passing necessary parameters (like cache_username, cache_password, jdg service name, jdg service port) to the client to authenticate/authorize JDG and how we are create SSLContext to encrypt the traffic between client and jdg server


Create secret first that would hold secret infromation (like cache_user, cache_password, keystore_user etc .. )

----
$ oc create secret generic client-secret --from-literal=cache_username=user1 --from-literal=cache_passwd=welcome1 --from-literal=keystore_password=changeit --from-literal=keystore_alias=selfsigned --from-literal=keystore_path=/etc/datagrid-secret-volume/jdg-https.jks
----

Now deploy the client

----
$ cd hotrod
$ mvn clean fabric8:deploy -DskipTests

# This command will compile the package and deploy the application into openshift. Wait for command to complete

# link client-secret to deployment config (you could have done as one step)
$  oc set env --from=secret/client-secret dc/hotrod
----

==== Step 4: Access Hotrod Client

Insert and retrieve data in JDG using hotrod client

----
$ oc get routes
datagrid-app          datagrid-app-jdg.192.168.99.100.nip.io                    datagrid-app          <all>                   None
hotrod                hotrod-jdg.192.168.99.100.nip.io                          hotrod                8080                    None
secure-datagrid-app   secure-datagrid-app-jdg.192.168.99.100.nip.io             secure-datagrid-app   <all>     passthrough   None

## Let's post some data
$ curl -i hotrod-jdg.192.168.99.100.nip.io/put/10

## you should receive "Successfully Inserted!" mesg if all goes well

$ curl -i hotrod-jdg.192.168.99.100.nip.io/get/10

## you should receive "Value is 10" message
----
