= JDG on Openshift with Hotrod and Security Enabled

=== Introduction

This demo aims to provide starting point/code-sample to configure and run Datagrid on Openshift with hotrod and authorization/authentication on

1. minishift v1.25.0+90fb23e
2. Openshift version v3.11.0
3. JBoss Datagrid Container Image 7.2
4. mvn 3.5.4

=== Run Demo
==== Step 1: Install minishift
Run following command to start minishift
----
$ minishift start --memory 8GB
----

==== Step 2: Download JBoss Datagrid Imagestream
----
$ oc login -u system:admin
$ oc project openshift
$ oc import-image registry.access.redhat.com/jboss-datagrid-7/datagrid72-openshift:1.3 --confirm
----

create 1.2 and latest tag
----
$ oc tag registry.access.redhat.com/jboss-datagrid-7/datagrid72-openshift:1.2 datagrid72-openshift:1.2
$ # tag latest to 1.3
$ oc tag registry.access.redhat.com/jboss-datagrid-7/datagrid72-openshift:1.3 datagrid72-openshift:latest
$
$ oc describe is/datagrid72-openshift
----
last command should show you three tags

==== Step 2: Deploy datagrid

First upload template that would deploy datagrid
----
$ oc project openshift
$ oc create -f templates/datagrid72-basic.json
$ oc new-project jdg
$ oc new-app --template=datagrid72-basic --name=rhdg \
            -e CACHE_NAMES=mycache \
            -e MYCACHE_CACHE_START=EAGER \
            -e USERNAME=user1 \
            -e PASSWORD=welcome1 \
            -e ADMIN_GROUP=customrole \
            -e CONTAINER_SECURITY_ROLES="customrole=READ WRITE" \
            -e HOTROD_AUTHENTICATION="true" \
            -e MYCACHE_CACHE_SECURITY_AUTHORIZATION_ENABLED="true" \
            -e MYCACHE_CACHE_SECURITY_AUTHORIZATION_ROLES="customrole" \
            -e HOTROD_SERVICE_NAME=datagrid-app-hotrod \
            -e REST_SECURITY_DOMAIN=jdg-openshift

----

Following parameters are passed in the above command

*CACHE_NAMES* = This will create "mycache" in JDG

*USERNAME* = To access JDG, username needs to be provided

*ADMIN_GROUP* = We create a new role, customrole, that we would assign privileges to

*CONTAINER_SECURITY_ROLES* = Here, we assign READ and WRITE privilege to customrole

*HOTROD_AUTHENTICATION* = Sets to true

*MYCACHE_CACHE_SECURITY_AUTHORIZATION_ENABLED* = This parameter (parameter starts with cache name, mycache, in CAPS) sets that authorization needs to be followed for mycache

*MYCACHE_CACHE_SECURITY_AUTHORIZATION_ROLES* = We assign customrole to MYCACHE cache

*HOTROD_SERVICE_NAME* = This maps to the service name that Openshift assigns when we deploy the template

For more information on setting environment variables, refer to this link for 7.2 version

https://access.redhat.com/documentation/en-us/red_hat_data_grid/7.2/html/data_grid_for_openshift/os-env-vars#env-var-cache

Now, check that user1 has been assigned customrole.

----
$ oc get pods
NAME                   READY     STATUS      RESTARTS   AGE
datagrid-app-2-lkhjz   1/1       Running     0          16m

$ oc rsh datagrid-app-2-lkhjz

sh-4.2$ cd /opt/datagrid/standalone/configuration
sh-4.2$ ls
application-roles.properties  clustered-openshift.xml  mgmt-groups.properties  standalone.xml
application-users.properties  clustered.xml       mgmt-users.properties   standalone_xml_history
cloud.xml      logging.properties       services.xml

sh-4.2$ cat application-roles.properties
...
...
...
user1=customrole

## You will see that in this file user1 is assigned customrole.
----

==== Step 3: Deploy Hotrod Client

We will now deploy client application (SpringBoot) which will access JDG in secure mode. Have a look at following two files
1. HotrodController.java - This file exposes all urls

2. HotrodService.java - This file initialize cache. Have a look at this file to understand how we are passing necessary parameters (like username, password, jdg service name, jdg service port) to the client to authenticate/authorize JDG.


----
$ cd hotrod
$ mvn clean fabric8:deploy -DskipTests

# This command will compile the package and deploy the application into openshift. Wait for command to complete

----

==== Step 4: Access Hotrod Client

Insert and retrieve data in JDG using hotrod client

----
$ oc get routes
NAME           HOST/PORT                                PATH      SERVICES       PORT      TERMINATION   WILDCARD
datagrid-app   datagrid-app-jdg.192.168.99.100.nip.io             datagrid-app   <all>                   None
hotrod         hotrod-jdg.192.168.99.100.nip.io                   hotrod         8080                    None

$ curl -i hotrod-jdg.192.168.99.100.nip.io/put/10

## you should receive "Successfully Inserted!" mesg if all goes well

$ curl -i hotrod-jdg.192.168.99.100.nip.io/get/10

## you should receive "Value is 10" message
----
